### PR TITLE
Fix unification of rigid type variables

### LINKED ISSUE #13: Type inference unifies rigid type variables
### Description

Our type inference algorithm does not fail when two rigid type variables bound by a type signature are matched with each other.

### Steps to Reproduce

1. Consider the following Haskell module

    ```haskell
    module Test where

    foo :: a -> b -> (a, a)
    foo x y = (x, y)
    ```

2. Compile `Test` with `freec` and `ghc` using the following commands.

    ```bash
    freec ./Test.hs
    ghc ./Test.hs
    ```

#### Expected behavior

In the example above the type signature specifies that `y` is of type `b` but `(x, y)` is of type `(a, a)` and thus `y` is also of type `a`. Since the type variables `a` and `b` may be distinct, `foo` is not type correct. Thus both `freec` and `ghc` should reject the definition.

#### Actual behavior

The GHC rightly rejects the definition of `foo` with the following error message.

```
Test.hs:4:15: error:
    • Couldn't match expected type ‘a’ with actual type ‘b’
      ‘b’ is a rigid type variable bound by
        the type signature for:
          foo :: forall a b. a -> b -> (a, a)
        at Test.hs:3:1-23
      ‘a’ is a rigid type variable bound by
        the type signature for:
          foo :: forall a b. a -> b -> (a, a)
        at Test.hs:3:1-23
    • In the expression: y
      In the expression: (x, y)
      In an equation for ‘foo’: foo x y = (x, y)
    • Relevant bindings include
        y :: b (bound at Test.hs:4:7)
        x :: a (bound at Test.hs:4:5)
        foo :: a -> b -> (a, a) (bound at Test.hs:4:1)
  |
4 | foo x y = (x, y)
  |               ^
```

However, `freec` just unifies `a` and `b` and produces the following Coq module.

```coq
(* module Test *)
From Base Require Import Free.
From Base Require Import Prelude.

Definition foo (Shape : Type) (Pos : Shape -> Type) {a : Type} 
   (x : Free Shape Pos a) (y : Free Shape Pos a)
   : Free Shape Pos (Pair Shape Pos a a)
 := @Pair_ Shape Pos a a x y.
```

### Versions

 - `freec --version`:
   `The Free Compiler, version 0.1.0.0 (v0.1.0.0-527-gfe1b9b0, ghc 8.6, linux, x86_64)`
 - `ghc --version`: 8.6.5
 - `cabal --version`: 2.4.1.0
 - OS: Ubuntu 19.10

### PR DESCRIPTION
**Pull request by just95**
The unification algorithm that is used by the type inference pass was extended to report a fatal error if a rigid type variable bound by the type signature of a function is matched with another type. Closes #13

### CODE REVIEW

File: src/lib/FreeC/Frontend/Haskell/Simplifier.hs [hunk 1]
```diff
@@ -480,11 +482,30 @@ simplifyTypeSchema (HSE.TyForall srcSpan (Just binds) Nothing typeExpr) = do
...
+ where
+  -- | Finds the first occurrence of the type variable with the given name.
+  --
+  --   Returns 'NoSrcSpan' if 'findTypeArgSrcSpan'' returns @Nothing@.
+  --   Since the type arguments have been extracted using 'freeTypeVars',
+  --   'findTypeArgSrcSpan'' should never return @Nothing@.
+  findTypeArgSrcSpan :: IR.Type -> IR.TypeVarIdent -> SrcSpan
+  findTypeArgSrcSpan = fromMaybe NoSrcSpan .: flip findTypeArgSrcSpan'
+
+  -- | Like 'findTypeArgSrcSpan' but returns @Nothing@ if there is
```
Comment (stu204767) [inline src/lib/FreeC/Frontend/Haskell/Simplifier.hs:499]:
```suggestion
  -- | Like 'findTypeArgSrcSpan', but returns @Nothing@ if there is
```

File: src/lib/FreeC/IR/Reference.hs [hunk 2]
```diff
@@ -93,6 +94,12 @@ refScope = fst . unwrapRef
 refName :: Ref -> IR.QName
 refName = snd . unwrapRef
 
+-- | Like 'refName' but unwraps the identifier of the name.
```
Comment (stu204767) [inline src/lib/FreeC/IR/Reference.hs:97]:
```suggestion
-- | Like 'refName', but unwraps the identifier of the name.
```

File: src/lib/FreeC/Pass/TypeInferencePass.hs [hunk 3]
```diff
@@ -758,15 +811,18 @@ applyFuncDeclVisibly funcDecl = withLocalTypeAssumption $ do
...
+abstractTypeArgs :: [IR.TypeVarIdent] -> IR.FuncDecl -> IR.FuncDecl
+abstractTypeArgs typeArgIdents funcDecl =
+  let
+    typeArgs                   = map (IR.UnQual . IR.Ident) typeArgIdents
+    IR.TypeSchema _ _ typeExpr = fromJust (IR.funcDeclTypeSchema funcDecl)
+    (IR.TypeSchema _ typeArgs' _, subst) =
+      abstractTypeSchema' typeArgs typeExpr
+    funcDecl' = applySubst subst funcDecl
+  in
+    funcDecl' { IR.funcDeclTypeArgs = typeArgs' }
```
Comment (stu204767) [inline src/lib/FreeC/Pass/TypeInferencePass.hs:825]:
```suggestion
  in funcDecl' { IR.funcDeclTypeArgs = typeArgs' }
```

File: src/test/FreeC/Monad/Class/Testable.hs [hunk 4]
```diff
@@ -83,14 +84,23 @@ shouldSucceedWith = flip (shouldReturnWith' (const "<expectation>")) id
 -- | Sets the expectation that the given computation fails without returning
 --   a value.
 shouldFail :: (Show a, MonadTestable m err) => m a -> Expectation
-shouldFail = flip shouldFailWith (const (return ()))
+shouldFail = flip shouldFailWith expectAnyError
+
+-- | Like 'shouldFail' but if the given computation does not fail, the
```
Comment (stu204767) [inline src/test/FreeC/Monad/Class/Testable.hs:89]:
```suggestion
-- | Like 'shouldFail', but if the given computation does not fail, the
```

File: src/test/FreeC/Monad/Class/Testable.hs [hunk 5]
```diff
@@ -83,14 +84,23 @@ shouldSucceedWith = flip (shouldReturnWith' (const "<expectation>")) id
...
+shouldFailPretty :: (Pretty a, MonadTestable m err) => m a -> Expectation
+shouldFailPretty mx = shouldFailWith' showPretty mx expectAnyError
 
 -- | Sets the expectation returned by the given function for the error
 --   that was produced by the given computation instead of a value.
 shouldFailWith
   :: (Show a, MonadTestable m err) => m a -> (err -> Expectation) -> Expectation
 shouldFailWith = shouldFailWith' show
 
+-- | Auxillary function for 'shouldFailWith' that allows arbitrary errors.
```
Comment (stu204767) [inline src/test/FreeC/Monad/Class/Testable.hs]:
```suggestion
-- | Auxiliary function for 'shouldFailWith' that allows arbitrary errors.
```

File: src/test/FreeC/Pass/TypeInferencePassTests.hs [hunk 6]
```diff
@@ -185,241 +185,275 @@ testTypeInferencePass = describe "FreeC.Analysis.TypeInference" $ do
...
-                ]
-              )
-              [ "length @a @b (xs :: List a) :: Prelude.Integer = case xs of {"
-                ++ "    Nil -> if true @b then 0 else 1;"
-                ++ "    Cons (x :: a) (xs' :: List a) ->"
-                ++ "      succ (length @a @b xs')"
-                ++ "  }"
-              ]
+  context "non-recursive functions" $ do
+    it "infers the types of simple simple non-recursive correctly"
```
Comment (stu204767) [inline src/test/FreeC/Pass/TypeInferencePassTests.hs]:
```suggestion
    it "infers the types of simple non-recursive functions correctly"
```

**Review by stu204767 — CHANGES_REQUESTED** [review]
Well written code, I couldn't find any major issues.
All of the suggestions I made are minor: Some typos, some (in my opinion) missing commas and one unnecessary line break.

File: src/lib/FreeC/Pass/TypeInferencePass.hs (hunk 3 above)
Comment (just95) [reply src/lib/FreeC/Pass/TypeInferencePass.hs:825]: This suggestion cannot be applied directly since Brittany would change it back. I'm not exactly sure why Brittany wants to change the formatting in this case, though. Moving the binding of `typeArgs` down to the binding of `funcDecl'` seems to work. However, I usually try to sort `let`-bindings topologically. Thus, I'd stick with with the current formatting.

**Review by nbun — APPROVED** [review]
Looks good to me!

File: src/lib/FreeC/IR/Subterm.hs [hunk 7]
```diff
@@ -261,6 +263,13 @@ findSubterms :: Subterm a => (a -> Bool) -> a -> [a]
 findSubterms predicate term =
   filter predicate (map (fromJust . selectSubterm term) (allPos term))
 
+-- | Gets the first subterm of the given expression that satisfies the
+--   provided predicate.
+--
+--   Return @Nothing@ if there is no such subterm.
+findFirstSubterm :: Subterm a => (a -> Bool) -> a -> Maybe a
+findFirstSubterm = listToMaybe .: findSubterms
+
```
Comment (ichistmeinname) [inline src/lib/FreeC/IR/Subterm.hs:272]: After reading this definition, I was wondering why the used function `findSubterms` uses `fromJust` rather than `catMaybes` to get rid of `Nothing`s afterwards. Do you really need the run-time error of `fromJust` to be triggered here? Yes, it's safe, because all positions of `term` should yield a valid sub term, but still I'm not sure this is the best way to go here.

Additionally, I was wondering if using [`First`](https://hackage.haskell.org/package/base-4.14.0.0/docs/Data-Semigroup.html#t:First) isn't the usual way to define a function like `findFirstSubTerm`, but perhaps it only overcomplicates the code -- not sure about that.

File: src/lib/FreeC/Frontend/Haskell/Simplifier.hs [hunk 8]
```diff
@@ -480,11 +482,30 @@ simplifyTypeSchema (HSE.TyForall srcSpan (Just binds) Nothing typeExpr) = do
...
+  --   no such type variable.
+  findTypeArgSrcSpan' :: IR.TypeVarIdent -> IR.Type -> Maybe SrcSpan
+  findTypeArgSrcSpan' = fmap IR.typeSrcSpan .: findFirstSubterm . isTypeVar
+
+  -- | Tests whether the given type is the type variable with the given name.
+  isTypeVar :: IR.TypeVarIdent -> IR.Type -> Bool
+  isTypeVar typeVarIdent (IR.TypeVar _ typeVarIdent') =
+    typeVarIdent == typeVarIdent'
+  isTypeVar _ _ = False
```
Comment (ichistmeinname) [inline src/lib/FreeC/Frontend/Haskell/Simplifier.hs:508]: Brittany does not want these function rules to be aligned, huh?

**Review by ichistmeinname — CHANGES_REQUESTED** [review]

File: src/lib/FreeC/IR/Subterm.hs (hunk 7 above)
Comment (just95) [reply src/lib/FreeC/IR/Subterm.hs:272]: I think the primary reason for using `fromJust` was consistency with `findSubtermPos` which cannot be expressed using `catMaybes`. The potential run-time error could actually be beneficial in this case. It allows us to spot mistakes in the implementation while `catMaybes` would silently ignore such bugs.

A better solution could be to add an alternative to `selectSubterm` that does not return a `Maybe` but prints are more useful error message than `fromJust` by mentioning the position of the subterm that could not be found. Such a function would be also useful since the pattern of removing `Maybe` from the result of `seletSubterm` can be found in [other parts of the code](https://github.com/FreeProving/free-compiler/blob/master/src/lib/FreeC/Backend/Coq/Converter/FuncDecl/Rec/WithHelpers.hs#L151) as well.

---

I'm not sure how you would use `First` in this case. It would be possible to replace `listToMaybe` with concatenation over the `Maybe (First a)` monoid. But as you've said already, that would just over complicate the code.

```haskell
import           Data.Semigroup                 ( First(..) )

findFirstSubterm :: Subterm a => (a -> Bool) -> a -> Maybe a
findFirstSubterm = fmap getFirst . mconcat . map (Just . First) .: findSubterms
```

File: src/lib/FreeC/Frontend/Haskell/Simplifier.hs (hunk 8 above)
Comment (just95) [reply src/lib/FreeC/Frontend/Haskell/Simplifier.hs:508]: As far as I know, Brittany does not align rules if one of them spans multiple lines.

File: src/lib/FreeC/Frontend/Haskell/Simplifier.hs (hunk 1 above)
Comment (just95) [reply src/lib/FreeC/Frontend/Haskell/Simplifier.hs:499]: According to [this article](https://www.grammarly.com/blog/comma-before-but/) a comma is put before *but* only if it connects two independent clauses. 
If the comment was `This function behaves like 'findTypeArgSrcSpan', but it returns @Nothing@ if there is no such type variable.`, I'd agree that a comma should be placed before *but* since both halves could be sentences on their own. However, in this case I'm not sure what's the correct punctuation. `Like 'findTypeArgSrcSpan'` doesn't sound like a full sentence to me. However, I could be wrong. @ichistmeinname  what do you think is the proper punctuation in this case?

File: src/lib/FreeC/IR/Subterm.hs (hunk 7 above)
Comment (ichistmeinname) [reply src/lib/FreeC/IR/Subterm.hs:272]: Should we add an issue for the modification of `selectSubterm` with a custom error message?

**Review by ichistmeinname — APPROVED** [review]

File: src/lib/FreeC/IR/Subterm.hs (hunk 7 above)
Comment (just95) [reply src/lib/FreeC/IR/Subterm.hs:272]: I've added an enhancement proposal #52.

File: src/lib/FreeC/Frontend/Haskell/Simplifier.hs (hunk 1 above)
Comment (stu204767) [reply src/lib/FreeC/Frontend/Haskell/Simplifier.hs:499]: I also looked at this article during my review and think that the comma should be there:
`Like 'findTypeArgSrcSpan'` may not be a full English sentence, but in this context it stands for a full sentence like the one you described and is therefore an independent clause.
This can also be seen by assuming `Like 'findTypeArgSrcSpan'.` were the entire comment for this function. While it would be strange to have two functions doing the same thing from a programming point of view, this would still be a sensible comment from a linguistic point of view.

**Review by stu204767 — APPROVED** [review]
